version: "3.9"

services:
    api:
        image: ghcr.io/budgetflix/budgetflix-api:dev
        container_name: budgetflix-api
        restart: unless-stopped
        env_files:
            - /opt/budgetflix/budgetflix.env


        volumes:
            - /srv/budgetflix:/budgetflix

        environment:
            - DB_PATH=/budgetflix/database/budgetflix.db
            - SPRING_PROFILES_ACTIVE=prod

            # RabbitMQ
            - SPRING_RABBITMQ_HOST=rabbitmq
            - SPRING_RABBITMQ_PORT=5672
            - SPRING_RABBITMQ_USERNAME=admin
            - SPRING_RABBITMQ_PASSWORD=admin

            - QUEUES_UPLOAD=video.upload
            - QUEUES_UPLOAD_RETRY=video.upload.retry
        
        depends_on:
            - rabbitmq

    worker:
        image: ghcr.io/budgetflix/budgetflix-worker:dev
        container_name: budgetflix-worker
        restart: unless-stopped

        volumes:
            - /srv/budgetflix:/budgetflix

        environment:
            - RABBITMQ_HOST=rabbitmq
            - RABBITMQ_PORT=5672
            - RABBITMQ_USERNAME=admin
            - RABBITMQ_PASSWORD=admin
            
            - NEW_DIR=/budgetflix/media/inbox/new
            - PROCESS_DIR=/budgetflix/media/inbox/process
            - DONE_DIR=/budgetflix/media/inbox/done
            - ERROR_DIR=/budgetflix/media/inbox/error
            - ERROR_LOG=/budgetflix/media/inbox/error/errorLog.txt
            - MOVIE_SOURCE=/budgetflix/media/library/movies
            - SERIES_SOURCE=/budgetflix/media/library/series

            - VIDEO_QUEUES_UPLOAD=video.upload
            - VIDEO_QUEUES_UPLOAD_RETRY=video.upload.retry

        depends_on:
            - rabbitmq

    rabbitmq:
        image: rabbitmq:3-management
        container_name: budgetflix-rabbitmq
        restart: unless-stopped

        ports:
            - "5672:5672"
            - "15672:15672"

        environment:
            - RABBITMQ_DEFAULT_USER=admin
            - RABBITMQ_DEFAULT_PASS=admin

        volumes:
            - rabbitmq_data:/var/lib/rabbitmq
            - /rabbitmq/definitions.json:/etc/rabbitmq/definitions.json

    nginx:
        image: nginx:latest
        container_name: budgetflix-nginx
        restart: unless-stopped

        ports:
            - "80:80"

        volumes:
            - /srv/budgetflix/media:/media
            - ./nginx/nginx.config:/etc/nginx/nginx.conf:ro

        depends_on:
            - api

volumes:
    rabbitmq_data: