version: "3.9"

services:
    api:
        image: ghcr.io/budgetflix/budgetflix-api:dev
        container_name: budgetflix-api
        restart: unless-stopped
        volumes:
            - /srv/budgetflix:/budgetflix
        environment:
            - DB_PATH=/budgetflix/database/budgetflix.db
            - SPRING_PROFILES_ACTIVE=prod

    worker:
        image: ghcr.io/budgetflix/budgetflix-worker:dev
        container_name: budgetflix-worker
        restart: unless-stopped
        volumes:
            - /srv/budgetflix:/budgetflix

    nginx:
        image: nginx:latest
        container_name: budgetflix-nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - /srv/budgetflix/media:/media
            - ./nginx/nginx.config:/etc/nginx/nginx.conf:ro
        depends_on:
            - api
